// Hancock Structural Steel, LLC's real "Standard Terms & Conditions of Sale"
// (12 articles), transcribed verbatim from the company's reference proposal
// template PDF so it can be seeded as company-hancock's OWN
// CompanyProposalTerms row in localData.js's buildSeedData() — that row is
// hard-scoped to company_id: 'company-hancock' and must never be used as a
// fallback/default for any other tenant. A newly created company gets no
// CompanyProposalTerms row at all and starts from ProposalTermsPanel.jsx's
// empty state ("No terms documents uploaded yet."), prompting its own admin
// to upload their own terms — this content is Hancock's real, proprietary
// legal text, not sample/placeholder copy for other companies to inherit.
//
// Format read by drawProposalTermsBody() in bidProposalPdfLayout.js:
//   - A line starting with "ARTICLE " is a top-level article heading.
//   - A line starting with a clause number ("1.1 ", "1.2.3 ", ...) is a
//     clause — the number is bolded, the rest of the line is normal weight.
//     A three-part number (e.g. "1.2.1") renders with an extra indent.
//   - Any other non-blank line is a plain paragraph (used only for the
//     closing confidentiality paragraph, which carries no clause number).
//   - Blank lines are paragraph breaks.
export const HANCOCK_PROPOSAL_TERMS_TEXT = `ARTICLE 1 – PROPOSAL TERMS AND CONTRACT DOCUMENTS:

1.1 These Standard Terms & Conditions of Sale are part of Hancock Structural Steel, LLC’s (“Seller”) Proposal (the “Proposal”). “Buyer” or “Buyer” means the Buyer listed in the Proposal.

1.2 PROPOSAL TERMS. This offer is expressly limited to these terms, and any attempt to add to such terms shall be deemed a rejection and a counteroffer, which may result in a withdrawal of this Proposal or a modification in price.

1.2.1 If this Proposal is accepted, and the Buyer’s order is issued for that purpose, it is expressly agreed that the terms and conditions of this Proposal shall prevail insofar as the same may in any way conflict with the terms and conditions set forth in the Buyer’s order form, and the issuance of such order form by the Buyer shall be deemed to be the Buyer’s assent to the foregoing.

1.2.2 If, as a result of this provision, Seller is asked or required to enter into a separate written agreement beyond the terms of this Proposal, then, in that event, Seller reserves the right to review the general terms and conditions of the proposed agreement and the right to reject any and all terms and conditions of said agreement which are in conflict with or vary the terms of this Proposal.

1.2.3 Time Limit of Proposal. Unless modified by the Proposal or given a directive to proceed resulting in a Contract as set forth in Article 1.3, the Proposal shall be valid for seven (7) days from the date provided thereon, and thereafter shall automatically terminate unless extended in writing by Seller. The Proposal is made with reference to steel prices in effect on the date of the Proposal. This Proposal may be changed or revoked at any time by Seller prior to acceptance.

1.3 CONTRACT. In the event, prior to the execution of a mutually agreeable contract, that Seller is directed to purchase material, begin the shop drawing process, or otherwise commence any of the work contemplated by this Proposal, this Proposal shall be deemed accepted, and becomes a binding agreement. Seller reserves the right to refuse or negotiate terms of any other proposed agreement presented by the Buyer as a substitution to these STANDARD TERMS & CONDITIONS OF SALE.

1.3.1 No terms and conditions contained in the agreement between Owner and Buyer, if applicable, shall be binding on Seller unless a copy of such terms and conditions has been furnished to Seller and accepted in writing signed by the Seller.

1.3.2 The parties expressly agree that this Proposal embodies their entire Contract; any subsequent cancellations or modifications must be agreed upon in writing.

1.3.3 Buyer and Seller agree that Seller’s Scope of Work is limited to the structural steel shown or noted on the structural design drawings only (“Work”).

1.3.4 Contract Documents. Unless agreed to by Seller in writing, the Contract Documents are limited to the plans and specifications specifically referenced in the Proposal and these Standard Terms & Conditions of Sale (“Contract Documents”). If there is any conflict among the provisions of the Proposal, these Standard Terms & Conditions of Sale, the referenced plans and specifications, or Buyer’s acceptance (hereinafter collectively called “Contract”), the documents shall govern in the order just given.

1.4 CODE OF STANDARD PRACTICE. Buyer and Seller agree that the Work shall be performed in accordance with the terms of these Standard Terms and Conditions of Sale and the American Institute of Steel Construction Code of Standard Practice for Buildings and Bridges (“CoSP”), in the addition specified in the Contract Documents, and if none is specified, the current edition of the CoSP.

1.5 PLANS AND SPECIFICATIONS. Seller shall be entitled to rely upon the plans and specifications provided to it by Buyer. Seller is not responsible for the suitability, adequacy, or building code conformance of the design or information provided by others, including the Contract Documents, nor does it assume responsibility for determining that the Owner’s requirements have been included in the design documents and specifications provided by others.

1.5.1 If the design is not complete at the time of the Proposal, released for construction drawings and approved shop drawings will be required before material purchases or fabrication can commence. Seller reserves the right to seek an equitable adjustment to the Contract Time or Contract Sum if the design drawings are incomplete.

1.6 SCOPE OF WORK. Materials will be fabricated in accordance with structural design drawings and specifications and with detailed shop drawings as approved by Owner or Owner’s authorized representatives (also known as “Products”). Seller will perform shop inspections in accordance with Owner’s requirements, to the extent they are expressly provided for in the structural steel specifications, as well as applicable AISC, AWS and AASHTO standards. Buyer, at its expense, must set, drill, grout, and tighten anchor bolts for steel members. Unless otherwise provided in the Proposal, Seller’s price does not include costs associated with field measurements, site surveys, shop inspection by independent 3rd party agencies, removal of hauling residue, field cleaning of any stain resulting from steel oxidization, field touch-up paint, painting, galvanizing, or supply of miscellaneous metals, embedded items, scuppers, drains, railings, conduit hangers or supports, shims, expansion dams, neoprene joints, sealing materials, grout, shear studs, or bolts other than connection bolts for supplied items.

1.7 PERMITS & LICENSES. Buyer shall obtain, without cost to Seller, all permits, licenses, easements, and environmental approvals necessary for the execution of the Contract.

ARTICLE 2 – TERMS OF PAYMENT:

2.1 CONTRACT SUM. The Contract Sum shall be as set forth on the face of the Proposal.

2.2 SCHEDULE OF VALUES. Seller will submit a Schedule of Values for progress invoicing.

2.3 TIME FOR PAYMENT. Payment shall be made to Seller within thirty (30) days of the date of Seller’s invoice.

2.4 REMEDIES FOR NON-PAYMENT. If Buyer does not pay Seller any amount due under this Contract or any other agreement when such amount is due, such shall be deemed in material breach of Contract, and Seller may, without liability to Buyer, and without prejudice to Seller’s other lawful remedies (i) terminate Seller’s obligations under this Contract; (ii) declare immediately due and payable all Buyer’s obligations to Seller; (iii) change credit terms with respect to any further work, including, but not limited to, receipt of cash in advance of further shipment for amounts owed or to be owed; (iv) suspend or discontinue any further work and, if suspended, the time to complete the Contract shall be extended for the period of such suspension; and/or (v) repossess the Products. The Contract amount shall be increased, by appropriate adjustment, by the amount of Seller’s demobilization, delay, and remobilization costs.

2.5 NO OFFSET OR SET-OFF. Buyer shall not set-off amounts due to any alleged claims against Seller on this Project or any other project.

2.6 SERVICE CHARGES. Payments not received when due shall incur service charges at the rate of one and a half percent (1.5%) per month (18% per annum) until paid.

2.7 NO CONTINGENT PAYMENTS. Payments due to Seller are not contingent upon payments by others nor shall Seller waive its lien rights prior to receiving payments due.

2.8 NO RETAINAGE. The Buyer agrees to pay the full purchase price stated in this Proposal. Retainage may not be withheld without the specific written consent of Seller. There will be no withholding of monies from Seller’s payments. Deductive change orders or back charges may not be withheld from any payments due Seller without written consent of Seller. Any disputed deductive change orders or back charges shall be resolved as set forth in Article 11.

2.9 NO PERFORMANCE OR PAYMENT BOND. The quoted price does NOT include the cost of a performance or payment bond Unless otherwise provided in the Proposal.

2.10 ADEQUATE ASSURANCES. In the event a reasonable doubt exists as to the Buyer’s financial responsibility, Seller shall have the right, in addition to all others it may possess, to stop operations, withhold shipment and recall in transit, and/or require a full or partial cash payment, until the Buyer shall have paid for all material previously delivered or satisfied Seller of Buyer’s financial responsibility and ability to pay the full Contract price. Seller shall have no obligation to begin or continue performance until adequate credit and funding information is provided, at any time on request of Seller. Seller may stop the manufacture or supply of any labor or materials when it, in its sole discretion, determines that Buyer is in breach of this Agreement or any other Contract with Seller or Seller has insecurity with respect to funding or creditworthiness, until payment is made, and any dispute or insecurity has been resolved.

2.11 LIEN WAIVERS: Nothing in the Contract Documents shall cause to be voided or diminished in any manner Seller’s right to enforce its mechanic’s lien rights or obtain payment under an applicable payment bond if Seller is not timely paid. Seller will only execute unconditional and/or final lien waivers for amounts actually received and any lien waivers shall only relate to the actual Work performed and not future Work or future payments. Any form or release wherein the Subcontractor purports to release the Contractor, Owner, or Design Professional is hereby qualified by the following language, whether or not the Subcontractor specifically adds the language: “This release shall apply only to work for which payment has been received in full by Seller, and it shall not apply to retainage, unbilled changes, or amounts not yet paid.”

ARTICLE 3 – LIMITATIONS ON WARRANTIES AND LIABILITIES:

3.1 DUTY TO INSPECT PRIOR TO ERECTION. All claims against Seller will be deemed waived unless made in writing within the earlier of, five (5) calendar days of delivery or two (2) days prior to erection. Claims against Seller will be waived unless Seller is given adequate opportunity to inspect, approve, and, if required, correct the cause of the claim. The provision includes, but is not limited to, errors, material defects, faulty workmanship, shortages, and assessments. A representative of Seller must authorize all claims. No claim will be allowed for corrections of alleged errors in materials fabricated by Seller unless Seller is notified before the corrections are made and Seller’s responsibility is proven.

3.2 LIMITED WARRANTY: Seller warrants that the work described in the Contract shall be free from defects in workmanship and material, which vary from the Contract Documents. Seller shall replace or repair any such faulty workmanship or defective material, which varies from the Contract Documents, provided that it is reported in writing to Seller (a) five (5) calendar days after delivery for defects which can be discovered upon a reasonable inspection, or (b) for latent defects, one (1) year from date of on which seller last delivers materials or services within the Scope of this Contract (“Warranty Period”). THE LIABILITY OF SELLER IS LIMITED TO THE REPAIR AND REPLACEMENT OF ANY DEFECTIVE MATERIALS OR PARTS THEREOF AT ITS SHOP, OR AT SUCH OTHER LOCATION AS SELLER, IN ITS SOLE OPTION SHALL DESIGNATE.

3.2.1 Seller shall be allowed time to inspect and verify a claim and shall have access to all performance data. No credit will be allowed for any cost or expense Buyer may incur in replacing or correcting materials or workmanship hereunder or for charges for labor or materials furnished by Buyer unless Buyer has obtained Seller’s prior written approval.

3.3 NO OTHER WARRANTIES. THE WARRANTIES SET FORTH IN THIS ARTICLE ARE EXCLUSIVE & IN LIEU OF ALL OTHER WARRANTIES WHETHER STATUTORY, EXPRESS, OR IMPLIED (INCLUDING ALL WARRANTIES OF MERCHANTABILITY & FITNESS FOR PARTICULAR PURPOSE AND/OR WARRANTIES ARISING FROM COURSE OF DEALING OR USAGE OF TRADE). THE REMEDIES PROVIDED ABOVE ARE THE BUYER’S SOLE REMEDIES FOR ANY FAILURE OF SELLER TO COMPLY WITH ITS OBLIGATIONS. SELLER HEREBY DISCLAIMS AND EXCLUDES ALL OTHER WARRANTIES. Any other statement in Contract Documents shall not be deemed to constitute a warranty.

3.4 LIMITATION OF REMEDIES. Corrections of non-conformities in the manner and for the period of time provided above shall constitute fulfillment of all liabilities of Seller to Buyer, whether based on warranty, contract, strict liability, negligence, willfulness or any other legal theory. IN NO EVENT SHALL SELLER BE LIABLE TO BUYER OR OTHER THIRD PARTIES FOR ANY SPECIAL, INDIRECT, INCIDENTAL OR CONSEQUENTIAL DAMAGES OR LOST PROFIT ARISING OUT OF OR IN ANY WAY CONNECTED WITH SELLER’S WORK UNDER THIS AGREEMENT.

3.5 ACCEPTANCE AND ACKNOWLEDGMENT. Acceptance of the Products shall occur if no written notice is made in writing, as set forth in Article 3.1, within the earlier of, five (5) calendar days of delivery or two (2) days prior to erection. By acceptance of the fabricated Products described on this Proposal, Buyer acknowledges that the limitations, disclaimers and terms set forth herein are conditions of the sale and that they constitute the entire agreement between Seller and Buyer regarding warranty or any other liability or damages.

3.6 DEFECTS BY OTHERS. Seller shall NOT be liable for any damages attributable to the Buyer or workmanship by others. THERE IS NO WARRANTY and Seller shall not be obligated to replace or repair all or any part of the work when such defects are not directly attributable to defects in Seller’ workmanship or material, such as, but not limited to, defects caused by operating abuse, neglect, erosion, corrosion, force majeure or other similar causes beyond Seller’ control.

3.7 PRODUCTS NOT FABRICATED BY SELLER. Seller’s sole obligation with respect to products not manufactured or produced by Seller or services directly rendered by Seller shall be limited to assigning or transferring to Buyer any written warranty extended to Seller by the manufacturer of such products or subcontractor of such services to the extent such warranty may be so assigned.

3.8 EFFECTIVE DATE OF WARRANTIES. The only warranties made by Seller are those expressly stated in this Article 3, and while it begins to run on the date of delivery, it shall not be effective until full and final payment of the Contract amount, including all adjustments thereto, has been received by Seller.

3.9 LIMITATION OF LIABILITY. The remedies of Buyer set forth in Article 3 are exclusive, and the total liability of Seller with respect to the Contract or anything done in connection therewith, such as the timeliness or quality of performance or lack thereof, whether in Contract, in tort (including negligence and strict liability), in warranty or otherwise shall not exceed ten percent (10%) of the amount paid to Seller on account of this Contract. Seller shall not be responsible for any liquidated damages or penalties related to time of performance or delays. Seller shall not be liable for work being done without its prior knowledge or consent.

ARTICLE 4 – INDEMNIFICATION:

4.1 Buyer hereby releases and agrees to indemnify, defend and hold harmless Seller, its shareholders, officers, agents, employees, affiliates, successors, assigns and third-party suppliers (“Seller’s Indemnified Parties”) from and against any and all direct and indirect claims, debts, actions, causes of action, liabilities, loss, suits, demands, fines, penalties, judgments, omissions, damages or expenses whatsoever, including, without limitation, attorneys’ fees and costs (“Damages”) incurred by or against Seller or any of Seller’s Indemnified Parties due to or arising out of, in connection with, resulting from or relating to (i) misrepresentations, breach of the warranties, representations, covenants or agreement contained in this Contract or any law by Buyer or any of Buyer’s shareholders, directors, officers, employees, affiliates, representatives, agents, successors or assigns (“Buyer’s Parties”), or (ii) any damage to or destruction of property, or injury to or death of persons caused, or alleged to have been caused, in whole or in part, by any intentional, reckless, negligent or other act (or failure to act) of Buyer or any of Buyer’s Parties, or (iii) losses, damages or injuries caused by Buyer’s products, Buyer’s specifications, designs, approvals or instructions provided to Seller, or due to improper application or use of the Products or otherwise. Prior to settling any claim, Buyer will give Seller an opportunity to participate in the defense and/or settlement of such claim. Buyer shall not settle any claim without Seller’s written consent. In the event of any recall affecting the Products, Seller shall have the right to control the recall process and Buyer shall fully cooperate with Seller in connection with the recall.

ARTICLE 5 – TITLE & RISK OF LOSS:

5.1 TITLE TO WORK. The title and right of possession of the Work shall remain in Seller whatever may be the mode of its attachment to realty or other property, until all payments are made in accordance with this Contract. Title shall pass to Buyer upon payment being fully made as set forth in this Contract.

5.2 RIGHT OF POSSESSION. Where Buyer has failed to make a payment within the allowed time, Seller may declare all remaining payments due and payable and, in exercise of its right of possession, shall have right of entry to the premises where the work is located and the right to remove the work from the premises. If the sum of the resale of salvage value of the work so removed and all payments made by Buyer exceeds the total damages (including consequential damages) to Seller, Seller will pay the excess amount to Buyer.

5.3 SECURITY INTEREST. Notwithstanding the foregoing, and as a precaution in case a court or an arbitrator deems title to the work to pass to Buyer prior to the full payment of the Contract price, Buyer hereby grants to Seller, in partial consideration for Seller’s sale of the Products and/or work, and Seller hereby retains a security interest in all Products sold to Buyer and documents relating to such Products or work now or hereafter in the possession of or under the control of Buyer, title to which might at any time be determined to have passed to Buyer including, without limitation, insurance proceeds and proceeds from the Buyer’s Contract with the owner listed therein, to secure Buyer’s obligations to Seller under this contract and all other obligations of Buyer to Seller. Buyer (i) authorizes Seller to execute, on Buyer’s behalf such financing statements, continuation statements and (ii) agrees to execute such other documents including, but not limited to pledge agreements, and to take such actions as may be required by Seller to evidence or perfect the security interest granted herein and the interest of Seller.

5.4 RISK OF LOSS. Buyer assumes all risk of loss after accepting care, custody, and control of any or all parts of the work. Owner or Buyer shall carry and maintain All Risk or Builder’s Risk insurance throughout the duration of the Project to cover all materials provided by Seller, and Seller shall be an additional named insured under such insurance policy.

ARTICLE 6 – CONTRACT TIME:

6.1 CONTRACT TIME. Seller shall only be bound to the project schedule to the extent it is specifically incorporated as a Contract Document on the face of this Proposal; otherwise, Seller shall perform the Work within a reasonable amount of time (“Contract Time”). If a schedule is expressly listed on the face of this Proposal, any modification to the agreed upon schedule shall allow Seller a reasonable time to complete its Work in an efficient manner considering the contract completion date and any interim times set forth in the project schedule. Seller’s ability to meet the required schedule is based on Buyer’s provision of contract drawings that comply with Section 3.1 of the AISC Code of Standard Practice at the time of bidding. Drawings must be clear and provide all details required for the preparation of shop drawings and fabrication. In the event RFIs are issued by Seller, schedule impacts should be expected.

6.1.1 In the absence of an agreed delivery schedule, Seller will produce, deliver and invoice as its production schedule permits, and Buyer’s failure to accept delivery or pay for stored materials on or before the Storage, Material & Delivery Escalation Date will make it subject to the Escalation Rate of two and a half (2.5%) per month for each month of delay on the unpaid portion of the Sale Price.

6.2 FORCE MAJEURE. If the performance of the Contract by Seller is interrupted by any cause beyond the reasonable control of Seller, whether similar or dissimilar, foreseen or unforeseen, foreseeable or unforeseeable, existing or future, Seller shall be excused from the performance of this Contract while and to the extent it is prevented from so performing by any one or more of such causes: (1) labor shortages, strikes, labor disputes, whether or not the demands of Seller shall be reasonable and within the power of either party to concede, or other inability to obtain necessary labor; (2) acts of God, including, but not limited to, epidemic, quarantine, flood, earthquake, wind, hurricane or other inclement weather; (3) changes in laws, proclamations, acts, regulations, ordinances, demands or requirements of any governmental authority; (4) explosions, accidents, sabotage, revolution or insurrection, acts of terrorism, civil commotion, blockade, embargo; (5) lack of or failure of or other inability to obtain necessary transportation, fuel, power, materials, machinery, raw materials, supplies, equipment or facilities, delays caused by other contractors, subcontractors or their subcontractors of any tier, or any materialmen or suppliers (including the suppliers of metal deck). Any such delay shall extend the time for completion of the Contract by not less than the duration of the delay. Additional costs incurred to complete, repair and/or replace any portion of the work due to a force majeure event shall be compensable to Seller, whether or not a change order for this work has been issued.

6.3 STORAGE COSTS AND MATERIALS. If the Buyer declines to accept delivery beyond the mutually agreed delivery date, a charge of $10.00 per square foot of space for storing raw and fabricated materials will be assessed to cover Seller’s storage, protection and finance costs; however, should Seller have to store materials offsite due to lack of available space, Buyer shall pay the actual storage costs incurred by Seller. Buyer shall also be responsible for paying for all temporary protection measures for such stored materials. Additionally, if the mutually agreed delivery date exceeds the Storage, Material & Delivery Escalation Date, the price shall be increased two and a half (2.5%) for each month of delay on the unpaid portion of the Sale Price beyond the Storage, Material & Delivery Escalation Date.

6.3.1 Handling costs incurred by Seller to move materials to and/or from the storage area or to handle material of other projects to accommodate storage of this project shall be charged at $100.00 per hour. Moving/handling equipment time will be charged at $485.00 per hour.

6.3.2 Buyer shall assume all risks for damage and weathering to any material stored at Buyer’s request.

6.4 EQUITABLE ADJUSTMENT. This Proposal is based upon: Seller’s timely receipt of Buyer’s notice to proceed; Issued for Construction Drawings, which comply with Section 3.1 of the AISC Code of Standard Practice, current edition; return of approved shop drawings as set forth in this Agreement; and prompt return of RFI responses to Seller. Seller shall be entitled to an equitable adjustment in the Contract Time and Contract Sum, including but not limited to, any increased costs of labor (including, but not limited to, rescheduling work, paint touch-up or repainting, additional handling, increases in labor or subcontract rates, etc.), overtime, and materials resulting from any change of drawings, change of schedule, acceleration, out of sequence work or delay caused by others for whom Seller is not responsible.

6.5 DELAYS OR SUSPENSIONS OVER 30 DAYS. To the extent the Project is suspended or delayed for a total of thirty (30) days, which days do not need to be consecutive, for causes beyond Seller’s control, Seller shall have the option to deem the Buyer in material breach, terminate the Contract, and stop work on the Project. If Seller elects to stop work due to this material breach, Seller shall be entitled to be paid for the value of work completed to date, including, but not limited to, stored materials, detailing, material and labor escalation, work in progress and any “wind down” expenses. In addition, Seller shall be entitled to its anticipated profit and overhead expense on the entire Contract, its unabsorbed shop overhead and expenses and its appurtenant costs and expenses, including, but not limited to, consulting and actual attorney’s fees.

ARTICLE 7 – CHANGES:

7.1 LIMITATION ON UNIT PRICES. Buyer recognizes that the prices in this Agreement are based upon Seller’s determination of the material and labor required to construct the structural steel elements based upon the Contract Documents listed in the Proposal. Changes made after the date of the Proposal shall be priced based on elements of the work and shall not be subject to unit prices.

7.2 DESIGN DRAWING CHANGES. Upon Seller’s receipt of the Released for Construction (“RFC”) drawings or subsequent changes to the RFC drawings, Seller shall review for variations and changes (“Design Drawing Changes”) from the bid documents included with this Contract. Seller shall be entitled to an equitable adjustment in the Contract Sum or Contract Time or both, in the event of increased quantities, complexity, labor, materials, or scope shown on the RFC drawings differ from the bid documents.

7.3 CONDITIONS PRECEDENT TO CHANGE ORDER WORK. Seller shall suspend performance of any change, whether directed by Buyer or suggested by Seller, unless the following conditions precedent are satisfied: (1) Seller is thereafter released in writing by Buyer to perform said change, (2) Buyer and Seller shall mutually agree in writing upon an equitable adjustment in the price and/or delivery date to reflect the effect of such change, (3) Buyer has timely paid all amounts owed under the original scope of Work in accordance with the Contract, (4) Buyer has reviewed and paid for all Buyer caused Changes within thirty (30) days of issuance of the change order request, (5) Buyer shall continue to make payments in accordance with the Contract Documents and (6) for Owner-caused Changes.

7.4 DIFFERING CONDITIONS. If conditions are encountered at the site which are concealed physical conditions which differ from those indicated in any plans, specifications, reports, surveys, or other information provided to Seller, then the Contract Sum shall be equitably adjusted for such concealed or unknown conditions by Change Order upon the claim of either party.

7.5 ESCALATION. Seller’s Contract Sum (including but not limited to labor, material, transportation prices) are based on current prices at the time of the Proposal. Any significant price increases (meaning a price increase exceeding 1.5% of the price at time of the Proposal) in materials, transportation, labor, or other services necessary to perform the Work that occur during the period of time between the date of the Proposal and substantial completion of the Project, shall cause the Contract Sum to be equitably adjusted by an amount reasonably necessary to cover any such increase. Likewise, if the completion of the Work is extended more than six (6) months beyond the anticipated substantial completion for such Work, then the Contract Sum shall also be equitably adjusted to account for inflation and rate increases.

ARTICLE 8 – DELIVERY & FREIGHT:

8.1 PAINT WARNING. Structural steel will be delivered with one (1) coat standard HSS shop primer. Your special attention is called to the use of extreme care and appropriate handling equipment required during unloading, rotation girders to web vertical position, erection, and subsequent field operations. Seller will not be responsible for any field touch-up required due to failure to properly protect the paint system after delivery F.O.B. jobsite.

8.2 DELIVERY. Delivery by truck will be F.O.B. destination with freight allowed to the nearest accessible point to the jobsite. Access is deemed to be an improved road that allows the truck to operate under its’ own power without jeopardizing the safe operation of the vehicle and the safety of the driver. The driver has full rights to assess the access and the right to deny delivery to the unloading point if he/she feels that he is jeopardizing his/her safety and/or the safe operation of the truck.

8.3 FREIGHT ALLOWANCE. The freight allowance does not include charges for unloading, switching, spotting, excess time, cartage, demurrage or other similar services, all of which will be additional charges to Buyer if performed by Seller, costs will be billed to Buyer at 120% of the costs billed to Seller.

8.3.1 The freight allowance for truck deliveries is based on full truckloads, should the Buyer request shipments requiring smaller loads than planned a corresponding change order will need to be issued and executed.

8.3.2 The freight allowance includes two (2) hours at the jobsite for unloading each truck delivery. Buyer agrees to promptly provide labor, cranes, or other equipment necessary to timely unload materials.

8.3.3 If Seller ships anchor bolts, bearings, embedded items, etc. in advance, Buyer will be responsible for unloading and providing a safe and secure storage of same.

8.3.4 Unless otherwise provided in the Proposal, truck deliveries will be weekdays, during Seller’s normal working hours. Shipments requiring after working hours delivery will be charged an additional amount of $500.00 per load.

8.3.5 All shipping materials used for hauling, crating, blocking, tie-downs, etc. shall remain the property of Seller. When necessary, Buyer, at no cost to Seller, must load onto Seller’s trucks all such shipping materials.

8.3.6 If Buyer cannot unload on the delivery day, Buyer shall be liable for (i) the expense of transporting the material back to the Seller’s plant and unloading, reloading, reshipping the material at a later date, or (ii) daily rental of shipping equipment left parked at the jobsite or staging area, and round trip expenses for Seller to retrieve all shipping equipment that was left. Buyer will be billed 120% of the costs billed to Seller by its vendor(s) for any other equipment rented or leased to deliver the material.

8.3.7 In the event Buyer is unable to unload the material from Seller’s equipment, Seller shall at its sole discretion determine whether equipment will be left at the jobsite, or the material returned to Seller’s facility. Charges arising under this Section shall be invoiced weekly and payment on such invoices shall be due in seven (7) days.

ARTICLE 9 – APPROVAL OF DRAWINGS:

9.1 APPROVAL OF SHOP DRAWINGS. Shop drawings will be prepared by Seller or its agents with all field measurements to be furnished by the Buyer. Written approval of shop drawings by the Buyer is required before fabrication. Shop drawings not approved within 14 calendar days will be cause for a time extension to the delivery schedule of fabricated material by Seller.

9.2 MEANING OF APPROVAL. When shop drawings prepared by Seller or its agents have been approved by the Buyer, such drawings shall be deemed a correct interpretation of the work to be performed and shall relieve Seller of any responsibility for defects or deficiencies arising out of work performed by Seller in accordance with such drawings.

9.3 INDEMNIFICATION. If any material shall be manufactured and/or sold by Seller to meet the Buyer’s particular specifications or requirements, the Buyer agrees to save Seller harmless against all claims for actual or alleged infringement of any United States or foreign patent and to defend any suits or actions which may be brought against Seller for any such infringement.

9.4 NO DESIGN RESPONSIBILITY. Seller excludes any design responsibility required by a registered engineer. Seller will prepare shop drawings in accordance with the A.I.S.C. Steel Specification Manual, current edition. Seller excludes stamping shop drawings and connection calculations by a registered engineer unless expressly listed on the face of the proposal.

ARTICLE 10 – INSPECTION & TESTING/TOLERANCES:

10.1 DELIVERED MATERIALS. Buyer shall inspect materials upon receipt for condition and completeness against the weight and shipping list, and if there is damage, a shortage, or nonconformance, Buyer may not return materials but note the damage, shortage, or nonconformance on the weight and shipping list and file a written claim with the carrier and Seller within five (5) days; otherwise, conformance, quality, and completeness shall be conclusively presumed and the Buyer will be deemed to have waived all claims. Seller will remedy damage or nonconformance by delivery of undamaged or conforming goods or by arranging for field repair, at its option, in which event Seller’s delivery obligations will be extended for a reasonable period of time.

10.2 TOLERANCES. All materials furnished or manufactured by Seller are subject to standard tolerances for variations, unless modified by the Contract Documents.

10.3 NO LIABILITY. Seller shall not be responsible for the correction of structural details prepared by others. Minor shop inaccuracies which are customarily corrected in the field shall not be subject to back charges. Seller shall not be responsible for damage to paint due to handling or exposure or other causes beyond the Seller’s control.

10.4 INSPECTION COSTS. Seller shall not be liable for charges by others for inspection and testing of material covered herein unless provided otherwise.

ARTICLE 11 – CLAIMS AND DISPUTE RESOLUTION:

11.1 NOTICE. Email communication sent from Seller to Buyer shall be considered official notification for items such as, but not limited to, changes, delays, suspension, and claims.

11.2 MEDIATION. Any claims arising out of or related to this contract shall be subject to mediation. Mediation shall be a condition precedent to arbitration. The request may be made concurrently with the filing of a demand for arbitration but, in such event, mediation shall proceed in advance of arbitration, which shall be stayed pending mediation for a period of 60 days from the date of filing, unless stayed for a longer period by agreement of the parties or court order. The parties shall share the mediator’s fee and any filing fees equally. The mediation shall be held in Findlay, Ohio, or at such other location as Seller may designate. Mediation shall be completed within 60 days of a demand for mediation.

11.3 ARBITRATION. All claims not resolved in mediation shall be subject to binding arbitration. Arbitration shall be governed by the Construction Industry Arbitration Rules of the American Arbitration Association. The parties shall mutually agree upon an arbitrator who is a construction lawyer with at least ten (10) years of construction law experience. The arbitrator shall require exchange by the parties of documents relevant to the issues raised by any claim, defense, or counterclaim on which the producing party may rely in support of or in opposition to any claim, defense, or counterclaim, with due regard for eliminating undue burden and expense and the expedited and lower cost nature of arbitration. At the request of a party, the arbitrator may at his or her discretion order the deposition of witnesses; however, depositions shall be limited to a maximum of three (3) depositions per party, each a maximum of six (6) hours duration, unless otherwise mutually agreed to by the parties. Any arbitration arising out of or relating to the Proposal may include, by consolidation or joinder, such additional persons or entities engaged or retained by contract in connection with this project who are signatories to arbitration provisions in agreements with one or more parties to the Proposal, provided however, that Seller shall not be unduly burdened by allocation of cost for such proceeding that is disproportionate to its relative matter in dispute, and further provided that the participation does not expand the obligations of participation beyond those expressly set out herein. By way of illustration only, and not limitation, Seller shall not be required to participate in expansive discovery of documents, deposition testimony or other costly and timely procedures merely because of its participation in such joint proceeding. The arbitration shall be held in Findlay, Ohio, or at such other location as Seller may designate. For disputes under $1,000,000.00, the parties agree that the arbitration shall be concluded within 180 days of the arbitration demand. For disputes over $1,000,000.00, the parties agree that the arbitration shall be concluded within one (1) year of the arbitration demand.

11.4 CHOICE OF LAW. The Contract shall be interpreted in accordance with the internal laws of the State where the Project is located (exclusive of its provisions regarding conflicts of laws).

ARTICLE 12 – MISCELLANEOUS PROVISIONS:

12.1 TERMINATION. If this Contract is terminated for any reason, Seller shall be entitled to be paid for the value of work completed to date, including, but not limited to, stored materials, detailing, material and labor escalation, and work in progress. In addition, Seller shall be entitled to its anticipated profit and overhead expense on the entire Contract, its unabsorbed shop overhead and expenses, and its appurtenant costs and expenses, including, but not limited to, consulting and actual attorney’s fees.

12.2 HEADINGS. The headings of these articles are solely for the convenience of the parties hereto, and, if there is any conflict between such headings and the rest of the Contract, the Contract shall control.

12.3 ASSIGNMENT. Buyer shall not assign, sell or, in any way, transfer its interest in this Contract without first obtaining prior written consent of Seller.

12.4 SUBCONTRACTS. Seller reserves the right, without notice to or written permission of Buyer, to subcontract any portion of the Contract, or assign any rights under this Contract, when it considers such action advisable.

12.5 TAXES. Except as otherwise stated in the Proposal, any tax under any present or future law, either state, federal or local including any import duties, taxes, charges or surcharges which may be imposed in the manufacture, shipment, sale, lease, possession, ownership or use of the work or any other similar tax imposed, shall be paid by Buyer, whether the same be determined or determinable at the time of completion and acceptance of the Contract or subsequent thereto. Buyer shall promptly reimburse Seller for such taxes (and related costs) arising out of the work for which the applicable law imposes responsibility for payment on Seller.

12.6 CONFIDENTIAL INFORMATION. Buyer acknowledges that all trade secrets, designs, shop drawings, engineering data, specifications and other Confidential Information (as defined below) which may be disclosed to it by Seller shall at all times, both during and after expiration or termination of this Contract for any reason, remain the exclusive property of Seller and that Buyer shall not acquire any proprietary interest whatsoever therein. “Confidential Information” means all knowledge and information disclosed by Seller to Buyer orally or in writing, or acquired by Buyer through observation, regarding Seller’s Products, technology, inventions, formulas, know-how, services, forecasts, sales methods, customer lists, customer usages and requirements, financial information, business plans, strategies and future business relationships, disclosed with the exception of such information which: (i) was already part of the public domain at the time of the disclosure by Seller; (ii) becomes part of the public domain through no fault of Buyer (but only after and only to the extent that it is published or otherwise becomes part of the public domain); (iii) was in Buyer’s possession prior to the disclosure by Seller and was not acquired, directly or indirectly, from Seller or from a third party who was under a continuing obligation of confidence to Seller; or (iv) is received (after the disclosure by Seller) by Buyer from a third party who did not require Buyer to hold it in confidence and did not acquire it directly or indirectly from Seller under a continuing obligation of confidence. Except as necessary to perform its duties under this Contract, Buyer shall not use or disclose any of such Confidential Information but shall use the greater of the degree of care required by this Contract or the same degree of care given its own trade secrets and confidential information. Upon expiration or termination of this Contract for any reason, Buyer shall, within 15 days, surrender to Seller all plans, drawings, specifications, sketches, pictures, films, tapes, computer disks, literature, samples, documents, other tangible objects and all copies thereof relating to trade secrets and other Confidential Information and all of Seller’s property. Buyer shall be permitted to destroy rather than return all analyses, extracts, and summaries prepared by Buyer, which contain Confidential Information, and such destruction shall be certified in writing to Seller by an authorized officer of Buyer who has supervised such destruction. Nothing in this Contract shall be construed to limit or negate the common or statutory law of torts or trade secrets where it provides Seller with broader protection than that provided herein.

12.7 SURVIVAL. The provisions found in these Terms and Conditions of Sale and any other provision the performance of or effectiveness of which naturally survives, shall survive expiration or termination of the parties’ agreement for any reason.

12.8 INVALIDITY/WAIVERS/REMEDIES: The invalidity in whole or in part of any condition of this instrument shall not affect the validity of the other conditions. The remedies herein reserved shall be cumulative and additional to any other remedies in law or in equity. No waiver of a breach of any provision hereof shall constitute a waiver of any other breach or of any other provision.

12.9 COPYRIGHT. Any copyright or other property or proprietary rights owned by Seller shall remain the exclusive property of Seller.

12.10 DRAFTING PARTY. Should any provision of this Contract require interpretation or construction, each Party acknowledges participation in the negotiation of this Contract and agrees that no provision of this Contract shall be construed against or interpreted to the disadvantage of any party hereto by any court or other governmental or judicial authority by reason of such party having or being deemed to have structured, dictated, or drafted such provision.

12.11 ENTIRE AGREEMENT. This instrument sets forth the entire agreement between the parties and supersedes all prior representations, understandings, or agreements of the parties, whether written or oral. The Agreement can be modified only in writing signed by both parties.

Any terms, conditions, pricing, or other bid information provided by Hancock Structural Steel, LLC, is confidential and proprietary trade secret information, the unauthorized disclosure of which is prohibited by law. As a condition of using Hancock Structural Steel, LLC’s terms, conditions, pricing, or other bid information in any bids or other disclosures expressly authorized by Hancock Structural Steel, LLC, you must agree not to otherwise disclose this information to suppliers, customers, competitors, or other entities or individuals that have not been expressly pre-approved by Seller.`;
